"""
Build "Desktop Helper.app" — a launcher bundle for the menu bar app.

Why a launcher bundle instead of a full py2app freeze: this is a personal app,
and the .app exists for two reasons — macOS permissions and login-item launch.
TCC only looks at the responsible app's Info.plist, so a thin bundle whose
executable launches the project's own uv environment gets us real permission
prompts ("Desktop Helper would like to access your calendar") without fighting
py2app over 2GB of PyTorch. The model weights, config, and code stay in the
project directory; the bundle just points at them.

usage:
    uv run python scripts/build_app.py            # builds ./Desktop Helper.app
    uv run python scripts/build_app.py --install  # also copies to /Applications

After building, launch it once and trigger each permission:
- ask a calendar question  → Calendars prompt (finally!)
- start a voice recording  → Microphone prompt
- the hotkey               → Desktop Helper appears in Accessibility to enable
"""
import argparse
import plistlib
import shutil
import stat
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
APP_NAME = "Desktop Helper"
BUNDLE_ID = "com.kai.desktop-helper"
LOG_PATH = "$HOME/Library/Logs/DesktopHelper.log"

INFO_PLIST = {
    "CFBundleName": APP_NAME,
    "CFBundleDisplayName": APP_NAME,
    "CFBundleIdentifier": BUNDLE_ID,
    "CFBundleExecutable": "DesktopHelper",
    "CFBundlePackageType": "APPL",
    "CFBundleShortVersionString": "0.1.0",
    "CFBundleVersion": "0.1.0",
    "LSMinimumSystemVersion": "13.0",
    # menu bar app: no Dock icon, no app switcher entry
    "LSUIElement": True,
    "CFBundleIconFile": "AppIcon",
    # never let LaunchServices translate the launcher under Rosetta (it did —
    # bash ran x86_64, breaking rubicon-objc's arch detection downstream)
    "LSArchitecturePriority": ["arm64"],
    # the whole point of the bundle — TCC reads these from the responsible
    # app's Info.plist; without them macOS silently refuses to even prompt
    "NSCalendarsFullAccessUsageDescription":
        "Desktop Helper reads today's events to answer questions about your calendar.",
    "NSCalendarsUsageDescription":
        "Desktop Helper reads today's events to answer questions about your calendar.",
    "NSRemindersFullAccessUsageDescription":
        "Desktop Helper reads your reminders to answer questions about your to-dos.",
    "NSRemindersUsageDescription":
        "Desktop Helper reads your reminders to answer questions about your to-dos.",
    "NSMicrophoneUsageDescription":
        "Desktop Helper records while you hold the hotkey so it can transcribe "
        "your question locally. Audio never leaves this Mac.",
    "NSAppleEventsUsageDescription":
        "Desktop Helper controls Spotify and other apps via AppleScript.",
}

LAUNCHER = """#!/bin/bash
# Desktop Helper launcher — generated by scripts/build_app.py
cd "{project}"
echo "--- Desktop Helper launched $(date) arch=$(uname -m) ---" >> "{log}"
# `arch -arm64` guards against LaunchServices translating script bundles
# under Rosetta, which flips uname/platform.processor and breaks
# rubicon-objc's architecture detection at import
exec arch -arm64 "{uv}" run python -m src.menubar >> "{log}" 2>&1
"""


def build(output_dir: Path) -> Path:
    uv = shutil.which("uv")
    if uv is None:
        sys.exit("uv not found on PATH — install it or adjust the launcher.")

    app = output_dir / f"{APP_NAME}.app"
    if app.exists():
        shutil.rmtree(app)
    macos_dir = app / "Contents" / "MacOS"
    macos_dir.mkdir(parents=True)

    with open(app / "Contents" / "Info.plist", "wb") as f:
        plistlib.dump(INFO_PLIST, f)

    launcher = macos_dir / "DesktopHelper"
    launcher.write_text(LAUNCHER.format(project=PROJECT_ROOT, uv=uv, log=LOG_PATH))
    launcher.chmod(launcher.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)

    icon = PROJECT_ROOT / "assets" / "AppIcon.icns"
    if icon.exists():  # generate with scripts/make_icon.py
        resources = app / "Contents" / "Resources"
        resources.mkdir()
        shutil.copy(icon, resources / "AppIcon.icns")

    # ad-hoc signature keeps the TCC grant stable across rebuilds; best-effort
    subprocess.run(["codesign", "--force", "--sign", "-", str(app)],
                   capture_output=True)
    return app


def main() -> None:
    parser = argparse.ArgumentParser(description=f"Build {APP_NAME}.app")
    parser.add_argument("--install", action="store_true",
                        help="copy the built app into /Applications")
    args = parser.parse_args()

    app = build(PROJECT_ROOT)
    print(f"Built {app}")

    if args.install:
        dest = Path("/Applications") / app.name
        if dest.exists():
            shutil.rmtree(dest)
        shutil.copytree(app, dest, symlinks=True)
        print(f"Installed {dest}")
        print("Add it to login items: System Settings → General → Login Items.")


if __name__ == "__main__":
    main()
